spring.application.name=backend1
spring.datasource.url=jdbc:mysql://localhost:3306/delivery_app
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration
# JWT
jwt.secret=deliveryApplicationJwtSecretKeyVerySecure123456789012345678901234567890
jwt.expiration=86400000

# ????
server.port=8080

# ????????? ???????? ??????????????
#logging.level.org.springframework.data.mongodb=ERROR

spring.security.oauth2.client.registration.google.client-id=120789838113-tv10pinvotgdv5gfpiums4l6rac1qnl5.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

spring.security.oauth2.client.registration.github.client-id=Ov23liupI160KVnCwB3A
spring.security.oauth2.client.registration.github.client-secret=e087d4d7f8f1da4c70a76b57eb3bb174209eb1bd


